### ISSUE TITLE
Sans-serif (Gothic) / Italic font face is not rendering

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/system-font-i18n-css#8]
The Sans-serif (Gothic) / Italic font face isn't rendering properly, instead rendering the normal (weight 400) font face.

### Expected Behavior

Visiting the documentation page (https://mirai.audio/system-font-i18n-css/#type__italic) should render the italic section in italics.

### Actual Behavior

The Italics section of the documentation is rendered in regular typeface.

## Tasks

* [ ] Update the definition of the italic font family to render properly in Italics
```css
@font-face {
  font-family: system-sans-serif;
  font-style: italic;
  font-weight: 400...
```
* [x] Create pull request

**Comment by 0xadada** [comment]
this seems to fix it, but not sure why:

```css
/* system-sans-serif

style:         sans-serif
variant:       Italic
weight:        400 (Regular)
unicode range: english (latin-1) and a bit more
 */
@font-face {
  font-family: system-sans-serif;
  font-style: italic;
  font-weight: 400;
  src:
    local(".SFNSText-Italic"),
    local("-apple-system"),  /* macOS */
    local("BlinkMacSystemFont"), /* macOS Chrome */
    local(".SFNSText"), /* macOS Firefox El Capitan+ */
    local(".HelveticaNeueDeskInterface-Regular"), /* macOS Yosemite */
    local(".LucidaGrandeUI"), /* macOS Kodiak-Mavericks */
    local("Noto Sans"), local("Roboto"), /* Linux, Chromebook, Android */
    local("Oxygen-Sans"), local("Ubuntu"), local("Cantarell"), /* KDE, Ubuntu, Gnome */
    local("Segoe UI"), local("Arial"); /* Window Phone, Windows Vista+ */
  unicode-range:
    U+0020-00FF, /* Basic-latin - Latin-1 Supplement */
    U+2000-206F, /* General Punctuation */
    U+2070-209F, /* Superscripts & subscripts */
    U+2150-218F, /* Number forms */
    U+2190-21FF, /* Arrows */
    U+2200-22FF; /* Mathmatical operators */
}
```
